// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tmsxfbrszqwsppmbkmmd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRtc3hmYnJzenF3c3BwbWJrbW1kIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzI4NTY3MDYsImV4cCI6MjA4ODQzMjcwNn0.xDq7IzmYPgqp6KRqL2iP17y0XmcW9lur3PRNsstYtkw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});